version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "java"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"