services:
  postgres-test:
    image: postgres:16
    container_name: my-postgres-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
    #command: mvn clean test -Dtest="com.dietiestate25backend.security.validation.**"
    #command: mvn clean test -Dtest="com.dietiestate25backend.security.auth.**"
    #command: mvn clean test -Dtest="com.dietiestate25backend.security.authorization.**"
    #command: mvn clean test -Dtest="com.dietiestate25backend.security.business.**"
    #command: mvn clean test -Dtest="com.dietiestate25backend.security.dataisolation.**"