package com.dietiestate25backend.error;

public enum ErrorCode {

    // 400 Bad Request
    INVALID_PAGE_SIZE,
    INVALID_PRICE,
    INVALID_PRICE_RANGE,
    INVALID_DIMENSION,
    INVALID_BATHROOMS,
    INVALID_RESPONSABILE,
    INVALID_ADDRESS,
    INVALID_CLIENT_ID,
    INVALID_VISIT_TIME,
    INVALID_USER_ID,
    INVALID_STATUS,
    INVALID_OFFERTA_STATUS,
    INVALID_DATE_FORMAT,
    INVALID_DATE_RANGE,
    INVALID_COORDINATES,
    INVALID_LATITUDE,
    INVALID_LONGITUDE,
    INVALID_CATEGORY,
    INVALID_REGISTRATION_ROLE,
    INVALID_STAFF_ROLE,
    INVALID_PASSWORD,
    ADDRESS_NOT_FOUND,
    DATE_NOT_IN_FORECAST,

    // 409 Conflict
    INVALID_IMMOBILE_ATTRIBUTES,
    EMAIL_ALREADY_IN_USE,
    USER_ALREADY_ASSOCIATED,

    // 404 Not Found
    IMMOBILE_NOT_FOUND,
    CLIENT_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    INVALID_CREDENTIALS,
    EMAIL_NOT_FOUND,
    OFFERTA_NOT_FOUND,
    ADMIN_NOT_FOUND,

    // 401 Unauthorized
    ACCOUNT_LOCKED,
    UNAUTHORIZED,
    INVALID_TOKEN,
    INSUFFICIENT_PERMISSIONS,

    // 500 Internal / Database / External
    DATABASE_WRITE_ERROR,
    DATABASE_READ_ERROR,
    INTERNAL_ERROR,
    EXTERNAL_SERVICE_ERROR
}